concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha
    }}
jobs:
  build:
    uses: ./.github/workflows/reusable-build.yml
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: adopt
        java-version: 11
    - continue-on-error: true
      name: Restore cache
      uses: actions/cache@v4
      with:
        key: deploy-${{ hashFiles('**/pom.xml') }}
        path: '~/.m2/repository

          ~/.cache/bower

          '
        restore-keys: 'deploy-

          '
    - continue-on-error: true
      if: runner.os == 'Linux'
      name: Build
      run: xvfb-run .github/scripts/build.sh deploy
      shell: bash
name: Build
on:
  repository_dispatch:
    types: trigger-ga___build.yml
