jobs:
  noResponse:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: lee-dohm/no-response@v0.5.0
      with:
        closeComment: 'This issue has been auto-closed as awaiting feedback for 30
          days. If you would like to continue discussing it, no problem! If you are
          the original author of this issue, any comment you make will trigger the
          bot to automatically re-open it (sometime in the next hour). If you are
          not the original author, you can still leave a comment, but it won''t trigger
          the bot to re-open the issue. Thanks!

          '
        daysUntilClose: 30
        responseRequiredLabel: awaiting feedback
        token: ${{ github.token }}
name: No Response
on:
  repository_dispatch:
    types: trigger-ga___no-response-bot.yml
